Chart.defaults.color = '#475569';
Chart.defaults.font.family = 'Inter, system-ui, -apple-system, sans-serif';
Chart.defaults.font.size = 12;
Chart.defaults.plugins.tooltip.backgroundColor = '#0f172a';
Chart.defaults.plugins.tooltip.borderColor = '#1e293b';
Chart.defaults.plugins.tooltip.borderWidth = 1;
Chart.defaults.plugins.tooltip.titleFont = { weight: '600', size: 13 };
Chart.defaults.plugins.tooltip.bodyFont = { size: 12 };
Chart.defaults.plugins.tooltip.padding = 10;
Chart.defaults.scale.grid.color = '#e2e8f0';
Chart.defaults.scale.ticks.color = '#475569';

function switchTab(id, btn) {
  document.querySelectorAll('.tab').forEach(t => {
    t.classList.remove('active');
    t.setAttribute('aria-selected', 'false');
  });
  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  document.getElementById('tab-' + id).classList.add('active');
  btn.classList.add('active');
  btn.setAttribute('aria-selected', 'true');
}
window.switchTab = switchTab;

// ─── AUTO-GENERATED FROM: mvload10.xlsx ──────────────────────────────────────
// Report Date : June 10, 2026
// Generated by MVIKAS Dashboard Processor

// NOTE: All monthly targets are TBD for June 2026
// Achieved = tonnage dispatched so far this month (June 2026)

const clients = [
  { name: 'Carrier Refrigeration',         person: 'Sangeet Dhasmana', target: 0, achieved: 61003.00, activeDays: 10 },
  { name: 'Bombax',                         person: 'Chirag Kumar',     target: 0, achieved: 39850.49, activeDays: 10 },
  { name: 'Carrier CTD',                    person: 'Deepak Sharma',    target: 0, achieved: 12415.03, activeDays: 10 },
  { name: 'Haier CCR',                      person: 'Shiva',            target: 0, achieved: 6556.01,  activeDays: 10 },
  { name: 'Loom Solar Pvt Ltd',             person: 'Deepak Sharma',    target: 0, achieved: 5540.00,  activeDays: 10 },
  { name: 'Cosmos Pumps Pvt Ltd',           person: 'Shiva',            target: 0, achieved: 2920.00,  activeDays: 10 },
  { name: 'Kumar Services',                 person: 'Deepak Sharma',    target: 0, achieved: 2059.96,  activeDays: 10 },
  { name: 'Sukuga Technologies Pvt Ltd',    person: 'Shiva',            target: 0, achieved: 1120.98,  activeDays: 10 },
  { name: 'Mitras Technocrafts Pvt Ltd',    person: 'Shiva',            target: 0, achieved: 760.05,   activeDays: 10 },
  { name: 'Frick India',                    person: 'Shiva',            target: 0, achieved: 585.00,   activeDays: 10 },
  { name: 'Oneiric Appliances Pvt Ltd',     person: 'Deepak Sharma',    target: 0, achieved: 541.00,   activeDays: 10 },
  { name: 'Vaidrishi Laboratories Pvt Ltd', person: 'Chirag Kumar',     target: 0, achieved: 479.80,   activeDays: 10 },
  { name: 'Grover Innovations LLP',         person: 'Shiva',            target: 0, achieved: 400.00,   activeDays: 10 },
  { name: 'Paramount Surgimed Ltd',         person: 'Deepak Sharma',    target: 0, achieved: 400.00,   activeDays: 10 },
  { name: 'Aurinko Healthcare Pvt Ltd',     person: 'Chirag Kumar',     target: 0, achieved: 55.00,    activeDays: 10 },
  { name: 'Global Impex',                   person: 'Anjali',           target: 0, achieved: 0,        activeDays: 10 },
  { name: 'Edusoft Healthcare Ltd',         person: 'Deepak Sharma',    target: 0, achieved: 0,        activeDays: 10 },
  { name: 'GCPA',                           person: 'Shiva',            target: 0, achieved: 0,        activeDays: 10 },
  { name: 'Pangea',                         person: 'Deepak Sharma',    target: 0, achieved: 0,        activeDays: 10 },
  { name: 'RSR',                            person: 'Deepak Sharma',    target: 0, achieved: 0,        activeDays: 10 },
  { name: 'Medical Science',                person: 'Chirag Kumar',     target: 0, achieved: 0,        activeDays: 10 },
  { name: 'Epson',                          person: 'Deepak Sharma',    target: 0, achieved: 0,        activeDays: 10 },
  { name: 'KRF',                            person: 'Not Alloted',      target: 0, achieved: 0,        activeDays: 10 },
  { name: 'Indu Sports',                    person: 'Chirag Kumar',     target: 0, achieved: 0,        activeDays: 10 },
];

clients.forEach(c => {
  c.pct = c.target > 0 ? Math.round(c.achieved / c.target * 100) : (c.achieved > 0 ? 999 : 0);
  c.avgDay = c.activeDays > 0 ? Math.round(c.achieved / c.activeDays) : 0;
  c.remaining = Math.max((c.target || 0) - c.achieved, 0);
  c.daysNeeded = c.avgDay > 0 && c.remaining > 0 ? parseFloat((c.remaining / c.avgDay).toFixed(1)) : (c.remaining === 0 ? 0 : 999);
});

const eddData = [
  { name: 'Bombax',                 count: 133 },
  { name: 'Carrier Refrigeration',  count: 57  },
  { name: 'Sukuga',                 count: 20  },
  { name: 'Carrier - CTD',          count: 12  },
  { name: 'Haier CCR',              count: 8   },
  { name: 'MITRAS',                 count: 4   },
  { name: 'Kumar Services',         count: 2   },
  { name: 'Loom Solar',             count: 2   },
  { name: 'Vaidrishi Laboratories', count: 1   },
  { name: 'Carrier Global',         count: 1   },
  { name: 'Aurinko Healthcare',     count: 2   },
];
const eddTotal = eddData.reduce((a, b) => a + b.count, 0);

const openData = [
  { name: 'Bombax',                   count: 403 },
  { name: 'Carrier Refrigeration',    count: 82  },
  { name: 'Sukuga',                   count: 22  },
  { name: 'Carrier - CTD',            count: 20  },
  { name: 'Haier CCR',                count: 19  },
  { name: 'MITRAS',                   count: 4   },
  { name: 'Cosmos Pumps Pvt. Ltd.',   count: 4   },
  { name: 'Frick India',              count: 4   },
  { name: 'Loom Solar',               count: 3   },
  { name: 'Kumar Services',           count: 2   },
  { name: 'Aurinko Healthcare',       count: 2   },
  { name: 'Carrier Global',           count: 1   },
  { name: 'Paramount Surgimed Ltd',   count: 1   },
  { name: 'Vaidrishi Laboratories',   count: 1   },
];
const openTotal = openData.reduce((a, b) => a + b.count, 0);

const dueData = [
  { name: 'Bombax',                 count: 37 },
  { name: 'Carrier Refrigeration',  count: 4  },
  { name: 'Haier CCR',              count: 2  },
  { name: 'Cosmos Pumps Pvt. Ltd.', count: 1  },
  { name: 'Carrier - CTD',          count: 1  },
];
const dueTotal = dueData.reduce((a, b) => a + b.count, 0);

const bookedData = [
  { name: 'Bombax',                 count: 31 },
  { name: 'Carrier Refrigeration',  count: 10 },
  { name: 'Cosmos Pumps Pvt. Ltd.', count: 2  },
  { name: 'Frick India',            count: 1  },
  { name: 'Haier CCR',              count: 1  },
];
const bookedTotal = bookedData.reduce((a, b) => a + b.count, 0);

const dailyTonnageData = [
  { name: 'Carrier Refrigeration',    kg: 4433.00 },
  { name: 'Bombax',                   kg: 2122.96 },
  { name: 'Cosmos Pumps Pvt. Ltd.',   kg: 958.00  },
  { name: 'Frick India',              kg: 110.00  },
  { name: 'Haier CCR',                kg: 34.00   },
];
const dailyTotal = dailyTonnageData.reduce((a, b) => a + b.kg, 0);

const monthlyTotal = clients.reduce((a, c) => a + c.achieved, 0);
const daysInMonth = 30; // June has 30 days
const activeDaysElapsed = 10;
const dailyAverage = monthlyTotal / activeDaysElapsed; // avg over active days

// ─── UPDATE HEADER ─────────────────────────────────────────────────────────────
const elDate = document.querySelector('.badge-date');
const elElapsed = document.querySelector('.badge-elapsed');
if (elDate) elDate.textContent = 'As of June 10, 2026';
if (elElapsed) elElapsed.textContent = '10 / 30 days elapsed · June 2026';

// ─── UPDATE KPI CARDS ─────────────────────────────────────────────────────────
document.getElementById('kpi-open').textContent = openTotal;
document.getElementById('kpi-edd').textContent = eddTotal;
document.getElementById('kpi-edd-pct').textContent = Math.round(eddTotal / openTotal * 100) + '% of open';
document.getElementById('kpi-due').textContent = dueTotal;
document.getElementById('kpi-booked').textContent = bookedTotal;
try { document.getElementById('kpi-booked').closest('.metric').querySelector('.metric-sub').textContent = 'June 10, 2026'; } catch(e){}
document.getElementById('kpi-daily-ton').innerHTML = dailyTotal.toLocaleString('en-IN', { maximumFractionDigits: 2 }) + ' <span style="font-size:0.9rem;font-weight:600">kg</span>';
document.getElementById('kpi-month-ton').innerHTML = monthlyTotal.toLocaleString('en-IN', { maximumFractionDigits: 2 }) + ' <span style="font-size:0.9rem;font-weight:600">kg</span>';
try { document.getElementById('kpi-month-ton').closest('.metric').querySelector('.metric-sub').textContent = 'June 2026 cumulative'; } catch(e){}
document.getElementById('kpi-daily-avg').innerHTML =
  dailyAverage.toLocaleString('en-IN', { maximumFractionDigits: 0 }) +
  ' <span style="font-size:0.9rem;font-weight:600">kg/day</span>';

// ─── OPEN SHIPMENTS TABLE (Panel 1) ───────────────────────────────────────────
const openTableBody = document.getElementById('open-table-body');
if (openTableBody) {
  openTableBody.innerHTML = '';
  openData.forEach((d, i) => {
    const eddCount = (eddData.find(e => e.name === d.name) || {}).count || 0;
    const dueCount = (dueData.find(e => e.name === d.name) || {}).count || 0;
    const pctDelayed = Math.round(eddCount / d.count * 100);
    const risk = pctDelayed >= 70 ? ['Critical','delayed'] : pctDelayed >= 40 ? ['High','delayed'] : pctDelayed >= 20 ? ['Medium','open'] : ['Low','due'];
    openTableBody.innerHTML += `<tr>
      <td style="color:#94a3b8;font-size:0.8rem">${i+1}</td>
      <td><strong>${d.name}</strong></td>
      <td>${d.count}</td>
      <td style="color:#dc2626;font-weight:600">${eddCount}</td>
      <td style="color:#d97706;font-weight:600">${dueCount}</td>
      <td style="color:${pctDelayed>=50?'#dc2626':'#d97706'};font-weight:700">${pctDelayed}%</td>
      <td><span class="badge ${risk[1]}">${risk[0]}</span></td>
    </tr>`;
  });
}

// ─── CHART 1: Status Donut ─────────────────────────────────────────────────────
new Chart(document.getElementById('statusDonut'), {
  type: 'doughnut',
  data: {
    labels: ['EDD Crossed (Delayed)', 'Open (in transit)', 'Due Tomorrow', 'Booked Yesterday'],
    datasets: [{
      data: [eddTotal, openTotal - eddTotal, dueTotal, bookedTotal],
      backgroundColor: ['#ef4444', '#3b82f6', '#f59e0b', '#10b981'],
      borderWidth: 2, borderColor: '#ffffff', hoverOffset: 6
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false, cutout: '68%',
    plugins: {
      legend: { display: false },
      tooltip: { callbacks: { label: ctx => ` ${ctx.label}: ${ctx.parsed}` } }
    }
  }
});

// ─── CHART 2: EDD Crossed by Customer ────────────────────────────────────────
new Chart(document.getElementById('eddBarChart'), {
  type: 'bar',
  data: {
    labels: eddData.map(d => d.name),
    datasets: [{
      label: 'EDD Crossed',
      data: eddData.map(d => d.count),
      backgroundColor: 'rgba(239,68,68,0.12)',
      borderColor: '#ef4444',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { beginAtZero: true, ticks: { font: { size: 11 } } },
      y: { ticks: { font: { size: 11, weight: '500' } }, grid: { display: false } }
    }
  }
});

// ─── CHART 3: Due Tomorrow (June 3) ───────────────────────────────────────────
new Chart(document.getElementById('dueTmrChart'), {
  type: 'bar',
  data: {
    labels: dueData.map(d => d.name),
    datasets: [{
      label: 'Due Tomorrow',
      data: dueData.map(d => d.count),
      backgroundColor: 'rgba(245,158,11,0.12)',
      borderColor: '#f59e0b',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { ticks: { autoSkip: false, maxRotation: 30, font: { size: 11, weight: '500' } }, grid: { display: false } },
      y: { beginAtZero: true }
    }
  }
});

// ─── CHART 4: Booked Yesterday (June 1) ───────────────────────────────────────
new Chart(document.getElementById('bookedChart'), {
  type: 'bar',
  data: {
    labels: bookedData.map(d => d.name),
    datasets: [{
      label: 'Booked Yesterday',
      data: bookedData.map(d => d.count),
      backgroundColor: 'rgba(16,185,129,0.12)',
      borderColor: '#10b981',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { ticks: { autoSkip: false, maxRotation: 30, font: { size: 11, weight: '500' } }, grid: { display: false } },
      y: { beginAtZero: true }
    }
  }
});

// ─── PANEL 2: Tonnage — note targets are TBD, showing achieved only ───────────
const barsEl = document.getElementById('tonnage-bars');
if (barsEl) {
  const clientsWithAchieved = clients.filter(c => c.achieved > 0).sort((a, b) => b.achieved - a.achieved);
  clientsWithAchieved.forEach(c => {
    barsEl.innerHTML += `<div class="client-row">
      <div class="client-name" title="${c.name}">${c.name}</div>
      <div class="client-person">${c.person}</div>
      <div class="prog-bar-wrap">
        <div class="prog-bar" style="width:100%;background:linear-gradient(90deg,#004df5,#3b82f6)"></div>
      </div>
      <div class="pct-text" style="color:#004df5;font-size:0.75rem">TBD</div>
      <div class="client-tonnage">${(c.achieved/1000).toFixed(2)}T</div>
    </div>`;
  });
}

const chartFont = { size: 11, weight: '500' };
const clientsWithAchieved = clients.filter(c => c.achieved > 0).sort((a, b) => b.achieved - a.achieved);
const top8 = clientsWithAchieved.slice(0, 8);

// ─── CHART 5: Achieved Tonnage (no targets available) ────────────────────────
new Chart(document.getElementById('targetChart'), {
  type: 'bar',
  data: {
    labels: top8.map(c => c.name),
    datasets: [{
      label: 'Achieved so far (kg)',
      data: top8.map(c => c.achieved),
      backgroundColor: 'rgba(0,77,245,0.12)', borderColor: '#004df5', borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      title: { display: true, text: 'Monthly targets are TBD for June 2026', font: { size: 11 }, color: '#94a3b8' }
    },
    scales: {
      x: { beginAtZero: true, ticks: { callback: v => (v/1000).toFixed(0)+'k', font: chartFont } },
      y: { ticks: { font: chartFont }, grid: { display: false } }
    }
  }
});

// ─── CHART 6: Achieved tonnage bar (since no target) ─────────────────────────
new Chart(document.getElementById('achChart'), {
  type: 'bar',
  data: {
    labels: top8.map(c => c.name),
    datasets: [
      { label: 'Achieved (kg)', data: top8.map(c => c.achieved), backgroundColor: 'rgba(16,185,129,0.15)', borderColor: '#10b981', borderWidth: 1.5, borderRadius: 4 }
    ]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: {
      legend: { position: 'bottom', labels: { boxWidth: 12, padding: 16, font: chartFont } },
      title: { display: true, text: 'June 2026 — Day 10 of month', font: { size: 11 }, color: '#94a3b8' }
    },
    scales: {
      x: { beginAtZero: true, ticks: { callback: v => (v/1000).toFixed(0)+'k', font: chartFont } },
      y: { ticks: { font: chartFont }, grid: { display: false } }
    }
  }
});

// ─── PANEL 3: Daily Average Table ─────────────────────────────────────────────
const tbody = document.getElementById('daily-table-body');
if (tbody) {
  clients.filter(c => c.achieved > 0).forEach(c => {
    tbody.innerHTML += `<tr>
      <td style="font-weight:600">${c.name}</td>
      <td style="font-size:0.8rem;color:#64748b">${c.person}</td>
      <td style="color:#94a3b8">TBD</td>
      <td>${c.achieved.toLocaleString('en-IN')}</td>
      <td style="color:#004df5;font-weight:700">—</td>
      <td>${c.activeDays}</td>
      <td>${c.avgDay.toLocaleString('en-IN')}</td>
      <td style="color:#94a3b8">TBD</td>
      <td style="color:#94a3b8">TBD</td>
    </tr>`;
  });
}

// ─── CHART 7: Avg kg/day ──────────────────────────────────────────────────────
const topAvg = clients.filter(c => c.avgDay > 0).sort((a, b) => b.avgDay - a.avgDay).slice(0, 10);
new Chart(document.getElementById('avgDayChart'), {
  type: 'bar',
  data: {
    labels: topAvg.map(c => c.name),
    datasets: [{ label: 'Avg kg/day', data: topAvg.map(c => c.avgDay), backgroundColor: 'rgba(99,102,241,0.12)', borderColor: '#6366f1', borderWidth: 1.5, borderRadius: 4 }]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { beginAtZero: true, ticks: { callback: v => v.toLocaleString('en-IN'), font: chartFont } },
      y: { ticks: { font: chartFont }, grid: { display: false } }
    }
  }
});

// ─── CHART 8: Days to Complete — skipped (targets TBD) ───────────────────────
const daysChartEl = document.getElementById('daysChart');
if (daysChartEl) {
  const ctx = daysChartEl.getContext('2d');
  ctx.font = '13px Inter, system-ui';
  ctx.fillStyle = '#94a3b8';
  ctx.textAlign = 'center';
  ctx.fillText('Monthly targets not yet set for June 2026', daysChartEl.width / 2, 80);
  ctx.fillText('This chart will populate once targets are assigned.', daysChartEl.width / 2, 105);
}

// ─── PANEL 4: KAM-wise breakdown ──────────────────────────────────────────────
const kamMap = {};
clients.filter(c => c.achieved > 0).forEach(c => {
  if (!kamMap[c.person]) kamMap[c.person] = { person: c.person, totalTarget: 0, totalAchieved: 0, clients: [] };
  kamMap[c.person].totalTarget += c.target;
  kamMap[c.person].totalAchieved += c.achieved;
  kamMap[c.person].clients.push(c);
});
const kamList = Object.values(kamMap).sort((a, b) => b.totalAchieved - a.totalAchieved);

const kamTbody = document.getElementById('kam-table-body');
if (kamTbody) {
  kamList.forEach(k => {
    kamTbody.innerHTML += `<tr>
      <td style="font-weight:700">${k.person}</td>
      <td>${k.clients.length}</td>
      <td style="color:#94a3b8">TBD</td>
      <td>${k.totalAchieved.toLocaleString('en-IN')}</td>
      <td style="color:#004df5;font-weight:700">—</td>
      <td>
        <div style="background:#e2e8f0;border-radius:99px;height:8px;overflow:hidden;width:120px">
          <div style="height:100%;border-radius:99px;width:100%;background:linear-gradient(90deg,#004df5,#3b82f6)"></div>
        </div>
      </td>
    </tr>`;
  });
}

new Chart(document.getElementById('kamDonut'), {
  type: 'doughnut',
  data: {
    labels: kamList.map(k => k.person),
    datasets: [{
      data: kamList.map(k => k.totalAchieved),
      backgroundColor: ['#004df5', '#10b981', '#f59e0b', '#ef4444', '#6366f1', '#ec4899'],
      borderWidth: 2, borderColor: '#fff', hoverOffset: 6
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false, cutout: '62%',
    plugins: {
      legend: { position: 'bottom', labels: { boxWidth: 12, padding: 12, font: { size: 11 } } },
      tooltip: { callbacks: { label: ctx => ` ${ctx.label}: ${(ctx.parsed / 1000).toFixed(2)}T` } }
    }
  }
});